#!/bin/bash

COLUMN_WIDTH=${RF_COLUMN_WIDTH:-30}
COLUMN_NUMBER=${RF_COLUMN_NUMB:-3}
LINE_LEN=${RF_LINE_WIDTH:-100}
LINE_LEN_ALIAS=0
TIMEFORMAT="Task completed in %3lR"
# working mode:
# 	loop: run inside while loop and user does not need to run with `run` command, just type the command user want
#	normal: run with `run` command: run task args
MODE=${RF_MODE:-loop}

RUNFILE_DIR="$(pwd)"
RUNFILE_FILE="${RUNFILE_DIR}/Runfile"
RUNFILE_FILE_BK="/tmp/RunfileBk"
AUTO_RELOAD=${RF_AUTO_RELOAD:-"yes"}

COLOR_RESET=$'\e[0m'
RED=$'\e[31m'
GREEN=$'\e[32m'
YELLOW=$'\e[33m'
BLUE=$'\e[34m'
