#!/bin/bash

##region EXPORT FN ==============================================================

rf_sed_padding() {
	# # Left justify with string length of 80
	# # sed -e :a -e ‘s/^.{1,80}$/& /;ta’
	# echo "${@}" | sed -e :a -e 's/^.\{1,78\}$/ &/;ta' >left_padding_wiht_space.txt
	# #
	# # Right justify with string length of 80
	# # sed -e :a -e ‘s/^.{1,80}$/ &/;ta’
	# echo "${@}" | sed -e :a -e 's/^.\{1,78\}$/& /;ta' >right_padding_wiht_space.txt
	# #
	# # Center with string length of 80.
	# # sed -e :a -e ‘s/^.{1,80}$/ & /;ta’
	# echo "${@}" | sed -e :a -e 's/^.\{1,77\}$/ & /;ta' >center_padding_space.txt

	# https://web.archive.org/web/20211206161803/http://sed.sourceforge.net/sed1line.txt
	# http://sed.sourceforge.net/sed1line.txt
	CONTENT="${1}"
	PADDING="${2}"
	LENGTH="${3}"
	TRG_EDGE="${4}"
	case "${TRG_EDGE}" in
	"left") echo "${CONTENT}" | sed -e :a -e "s/^.\{1,${LENGTH}\}$/${PADDING}&/;ta" ;;
	"right") echo "${CONTENT}" | sed -e :a -e "s/^.\{1,${LENGTH}\}$/&${PADDING}/;ta" ;;
	"center") echo "${CONTENT}" | sed -e :a -e "s/^.\{1,${LENGTH}\}$/${PADDING}&${PADDING}/;ta" ;;
	esac
	#echo -e "${RET__DONE}"
	return ${RET__DONE}
}

rf_sed_remove_empty_line() {
	# remove all empty line, need '' after -i on macos, can use ^$ to catch the empty line
	# and ^\s*$ for emtpy line with space (\s*)
	sed -i "" "/^[[:blank:]]*$/d" "${1}"
}
rf_sed_remove_comment_line() {
	# remove all comment lines, line start with space or tab too
	# ex:
	# # comment text
	#     # comment text
	#			# comment text
	sed -i "" "/^[[:blank:]]*#/d" "${1}"
}
rf_sed_remove_all_occur() {
	# delete all matching ${1}
	sed -i "" "/${1}/d" "${2}"
}
rf_sed_replace_first_occur() {
	# replace ${1} with ${2} - sed '1,/string/ s/string/replacement/' file
	sed -i "" "1,/${1}/ s/${1}/${2}/" ${3}
}
rf_sed_replace_all_occur() {
	sed -i "" "s/${1}/${2}/g" ${3}
}
##endregion =====================================================================

##region INTERNAL FN ============================================================

##endregion =====================================================================
